Ibrapp/ibrapp/home/urls.py
from django.urls import path
from . import views
from .views import PostListView,PostCreateView,PostUpdateView,PostDeleteView,PostDetailView,UserPostListView

urlpatterns = [
    path('',views.home,name='home-main'),
    path('store/',views.store,name='store-main'),
    path('suggest/',PostListView.as_view(),name='suggest-main'),
    path('user<str:username>', UserPostListView.as_view(), name='suggest-userposts'),
    path('suggest/new/',PostCreateView.as_view(),name='suggest-create'),
    path('suggest/<int:pk>/update/',PostUpdateView.as_view(),name='suggest-update'),
    path('suggest/<int:pk>/delete/', PostDeleteView.as_view(), name='suggest-delete')
]

Ibrapp/ibrapp/ibrapp/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',user_views.register,name='register'),
    path('profile/',user_views.profile,name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),

    #path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    #path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    #path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),


    path('',include('home.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ibrapp/ibrapp/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__ (self):
        return self.content

    def get_absolute_url(self):
        return reverse('suggest-main')

Ibrapp/ibrapp/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# Create your models here.

class profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg',upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} profile'
    def save(self, *args,**kwargs):
        super().save(*args,**kwargs)

        img = Image.open(self.image.path)

        if img.height > 200 or img.width > 200:
            output_size = (200,200)
            img.thumbnail(output_size)
            img.save(self.image.path)

Ibrapp/ibrapp/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import profile
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = ['image']

Ibrapp/ibrapp/home/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,get_object_or_404
from .models import Post
from django.views.generic import ListView, DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User

# Create your views here.
def home(request):
    return render(request, 'home/home.html')




def store(request):
    return render(request, 'home/store.html')




class PostListView(LoginRequiredMixin,ListView):
    model = Post
    template_name = 'home/suggest.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 6

class UserPostListView(LoginRequiredMixin,ListView):
    model = Post
    template_name = 'home/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 6

    def get_queryset(self):
        user = get_object_or_404(User,username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')



class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    fields = ['content']
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)



class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Post
    fields = ['content']
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Post
    success_url='/profile/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


@login_required
def suggest(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'home/suggest.html', context)

Ibrapp/ibrapp/users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, ProfileUpdateForm,UserUpdateForm


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Your account has been created! You can now login')
            return redirect('login')
    else:
        form = UserRegisterForm()

    return render(request,'users/register.html',{'form':form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST,instance=request.user)
        p_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form':u_form,
        'p_form':p_form
    }

    return render(request, 'users/profile.html',context)

Ibrapp/ibrapp/home/templates/home/base.html
<!DOCTYPE html>
<!--
/*

 =========================================================
 * Gaia Bootstrap Template - v1.0.1
 =========================================================

 * Product Page: https://www.creative-tim.com/product/gaia-bootstrap-template
 * Copyright 2017 Creative Tim (http://www.creative-tim.com)
 * Licensed under MIT (https://github.com/creativetimofficial/gaia-bootstrap-template/blob/master/LICENSE.md)

 =========================================================

 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 */
-->
<html lang="en">

<head>
    <meta charset="utf-8" />
    <!--TAB ICONS HERE!!! -->
    <link rel="apple-touch-icon" sizes="76x76" href="#">
    <link rel="icon" type="image/png" sizes="96x96" href="#">

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Index.html</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    {% load static %}
    <link href="{% static 'home/assets/css/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'home/assets/css/gaia.css' %}" rel="stylesheet"/>


    <!--     Fonts and icons     -->
    <link href='https://fonts.googleapis.com/css?family=Cambo|Poppins:400,600' rel='stylesheet' type='text/css'>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'home/assets/css/fonts/pe-icon-7-stroke.css' %}"  rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>


</head>

<body>

    <a href="#top"></a>
    <nav class="navbar navbar-default navbar-transparent navbar-fixed-top" color-on-scroll="200">
        <!-- if you want to keep the navbar hidden you can add this class to the navbar "navbar-burger"-->
        <div class="container">
            <div class="navbar-header ">
                <button id="menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a href="#top" class="navbar-brand">
                    CraftingSerendipities
                </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right navbar-uppercase">
                    <li>
                        <a href="{% url 'home-main' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'profile' %}">profile</a>
                    </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'store-main' %}">Store</a>
                    </li>
                    <li>
                        <a href="{% url 'suggest-main' %}">Suggestions</a>
                    </li>
                    <li class="dropdown">
                        <a href="#gaia" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-share-alt"></i> SUPPORT ME
                        </a>
                        <ul class="dropdown-menu dropdown-danger">
                            <li>
                                <a href="https://www.facebook.com/CraftingSerendipities-1804284502994242/?ref=nf&hc_ref=ARSq30qj9U45m8F1HW1dKzU6J5lgOSsjIc4helKsm0hv4yPZVujtVFdm7-OlKqJlolk"><i class="fa fa-facebook-square"target="_blank"></i> Facebook</a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/craftingserendipities/?hl=en"><i class="fa fa-instagram"target="_blank"></i> Instagram</a>
                            </li>
                        </ul>
                    </li>

                    {% if user.is_authenticated %}
<li>
                        <a class="dropdown-toggle btn btn-danger btn-fill" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a class="dropdown-toggle btn btn-danger btn-fill" href="{% url 'register' %}">Register</a>
                    </li>
                    <li>
                        <a class="dropdown-toggle btn btn-danger btn-fill" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
    </nav>

{% block NavBar %}

    <div class="section section-header">
        <div class="parallax filter filter-color-red">
            <div class="image"
            style="background-image: url('{%static 'home/assets/img/headerbg1.jpg' %}')">
        </div>
        <div class="container">
            <div class="content">
                <div class="title-area">
                    <p>Reem Hassan</p>
                    <h1 class="title-modern">Crafting Serendipities</h1>
                    <h3>unique, handmade polymer clay and resin accessories</h3>
                        <div class="separator line-separator">♦</div>
                    </div>
                <h2>Home</h2>

                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock NavBar %}


{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{message}}
        </div>
    {% endfor %}
{% endif %}


{% block content %}{% endblock content %}

{% block suggestmain %}
<div class="section section-small section-get-started">
    <div class="parallax filter">
        <div class="image"
        style="background-image: url('{% static 'home/assets/img/office-1.jpeg' %}')">
    </div>
    <div class="container">
        <div class="title-area">
            <h2 class="text-white">Give me you suggestions Now!!</h2>
            <div class="separator line-separator">♦</div>
            <p class="description">Thank you for your support and patience! If you have any suggestions on what to make next make sure to leave them here!</p>
        </div>

        <div class="button-get-started">
            <a href="{% url 'suggest-main' %}" class="btn btn-danger btn-fill btn-lg">Suggest Now!</a>
        </div>
    </div>
</div>
</div>
{% endblock suggestmain %}


 <footer class="footer footer-big footer-color-black" data-color="black">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-4">
                <div class="info">
                    <h5 class="title">Company</h5>
                    <nav>
                        <ul>
                            <li>
                                <a href="{% url 'home-main' %}">Home</a></li>
                                <li>
                                    <a href="{% url 'suggest-main' %}">Suggestions Page</a>
                                </li>
                                <li>
                                    <a href="{% url 'store-main' %}">Store</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>

                <div class="col-md-4 col-sm-4">
                    <div class="info">
                        <h5 class="title">Latest News</h5>
                        <nav>
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-instagram"></i> <b>NEW Anime Piece</b> Check it OUT!
                                        <hr class="hr-small">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-facebook-square"></i><b> NEW FACEBOOK EXCLUSIVE Tutorial </b>! Check it OUT!! Thank you everybody or whatever
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-md-3 col-md-offset-1 col-sm-4">
                    <div class="info">
                        <h5 class="title">Follow me on</h5>
                        <nav>
                            <ul>
                                <li>
                                    <a href="https://www.facebook.com/CraftingSerendipities-1804284502994242/?ref=nf&hc_ref=ARSq30qj9U45m8F1HW1dKzU6J5lgOSsjIc4helKsm0hv4yPZVujtVFdm7-OlKqJlolk" class="btn btn-social btn-facebook btn-simple" target="_blank">
                                        <i class="fa fa-facebook-square"></i> Facebook
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.instagram.com/craftingserendipities/?hl=en" class="btn btn-social btn-dribbble btn-simple" target="_blank">
                                        <i class="fa fa-instagram"></i> Instagram
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <hr>
            <div>
                Designed by Ibrahim Saeed
            </div>

        </div>
    </footer>

</body>

<!--   core js files    -->
<script src="{% static 'home/assets/js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'home/assets/js/bootstrap.js' %}" type="text/javascript"></script>

<!--  js library for devices recognition -->
<script type="text/javascript" src="{% static 'home/assets/js/modernizr.js' %}"></script>

<!--  script for google maps   -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

<!--   file where we handle all the script from the Gaia - Bootstrap Template   -->
<script type="text/javascript" src="{% static 'home/assets/js/gaia.js' %}"></script>

</html>

Ibrapp/ibrapp/home/templates/home/home.html
{% extends "home/base.html" %}
{% block content %}
<div class="section">
        <div class="container">
            <div class="row">
                <div class="title-area">
                    <h2>What I Do</h2>
                    <div class="separator separator-danger">✻</div>
                    <p class="description">I make special pieces out of polymer clay and resin inspired by everything around me</p>
                </div>
            </div>
            <div class="row ">
                <div class="col-md-4  ">
                    <div class="info-icon">
                        <div class="icon text-danger">
                            <img class="ServiceLogos" src="static/home/assets/img/ServicesLogo1.jpg">
                        </div>
                        <h3>Entertainment</h3>
                        <p class="description">I make items inspired by your favourite tv shows, movies and even anime shows</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="info-icon">
                        <div class="icon text-danger">
                            <img class="ServiceLogos"src="static/home/assets/img/ServicesLogo2.png">
                        </div>
                        <h3>Food</h3>
                        <p class="description">I have a wide variety of miniature food charms to choose your favourite from!</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="info-icon" style="position: relative;">
                        <div class="icon text-danger">
                         <img class="ServiceLogos" src="static/home/assets/img/ServicesLogo3.jpg">
                     </div>
                     <h3>Nature</h3>
                     <p class="description">I make individual polymer clay flowers and succulent jewellery that are perfect for summer! </p>
                 </div>
             </div>
         </div>
     </div>
 </div>
</div>


<div class="section section-our-team-freebie">
    <div class="parallax filter">
        <div class="image" style="background-image:url('static/home/assets/img/Mainbg7.png')">
        </div>
        <div class="container">
            <div class="content">
                <div class="row">
                    <div class="title-area">
                        <h2>Who We Are?</h2>
                        <div class="separator separator-danger">✻</div>
                        <p class="description"></p>
                    </div>
                </div>

                <div class="team">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card card-member">
                                        <div class="content">
                                            <div class="avatar avatar-danger">
                                                <img alt="..." class="img-circle" src="static/home/assets/img/BobRossPepe.png"/>
                                            </div>
                                            <div class="description">
                                                <h3 class="title">Reem Hassan</h3>
                                                <p class="small-text">Artirst</p>
                                                <p class="description">My name is Reem, I'm a 16 year old student at Queen International School, I have always been interested in crafts and arts, so in 2014 i have picked up polymer clay crafting and fell in love with it ever since.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="section section-freebie">
    <div class="container">
        <div class="title-area">
            <h5 class="subtitle text-gray">Here are some of</h5>
            <h2>My Personal Favourites</h2>
            <div class="separator separator-danger">∎</div>
            <h5>Ones that I truly adore and enjoyed making </h5>
        </div>
        <center>
              <img src="static/home/assets/img/Fav1.jpg"class="FavImg">
              <img src="static/home/assets/img/Fav2.jpg"class="FavImg">
              <img src="static/home/assets/img/Fav3.jpg"class="FavImg">
              <img src="static/home/assets/img/Fav4.jpg"class="FavImg">
        </center>

      <hr>
      <div class="button-get-started">
        <a href="#gaia" class="btn btn-danger btn-fill btn-md">Click to view full collection</a>
    </div>
</div>
</div>

{% endblock content %}

Ibrapp/ibrapp/home/templates/home/post_confirm_delete.html
{% extends "home/base.html" %}
{% block NavBar %}
{% load static %}

    <div class="section section-header-freebie">
        <div class="parallax filter filter-color-red">
            <div class="image"
            style="background-image: url('{%static 'home/assets/img/Mainbg4.jpg' %}')">
        </div>
        <div class="container">
            <div class="content">
                <div class="title-area">
                    <h1>Post Suggestion</h1>
                        <div class="separator line-separator">♦</div>
                    </div>

                    <div class="button-get-started"style="margin-bottom:40px;">
                        <a href=" {% url 'suggest-main' %}" class="btn btn-white btn-fill btn-lg ">
                            Back To Suggestions List
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock NavBar %}


{% block content %}
<div class="section container">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2> Are you sure you wsant to delete the post</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-danger btn-fill" type="submit">Yes, Delete</button>
                <a class="btn btn-danger btn-fill" href="{% url 'profile' %}">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block suggestmain %}{% endblock suggestmain %}

Ibrapp/ibrapp/home/templates/home/post_form.html
{% extends "home/base.html" %}
{% block NavBar %}
{% load static %}

    <div class="section section-header-freebie">
        <div class="parallax filter filter-color-red">
            <div class="image"
            style="background-image: url('{%static 'home/assets/img/Mainbg4.jpg' %}')">
        </div>
        <div class="container">
            <div class="content">
                <div class="title-area">
                    <h1>Post Suggestion</h1>
                        <div class="separator line-separator">♦</div>
                    </div>

                    <div class="button-get-started"style="margin-bottom:40px;">
                        <a href=" {% url 'profile' %}" class="btn btn-white btn-fill btn-lg ">
                            Back To profile
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock NavBar %}

{% load crispy_forms_tags %}
{% block content %}
<div class="section container">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Post Suggestion</legend>
                {{form|crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-danger btn-fill" type="submit">Post</button>
            </div>
        </form>
        <hr>
    </div>
</div>
{% endblock content %}

{% block suggestmain %}{% endblock suggestmain %}

Ibrapp/ibrapp/home/templates/home/store.html
{% extends "home/base.html" %}
{% block NavBar %}
{% load static %}
    <div class="section section-header">
        <div class="parallax filter filter-color-red">
            <div class="image"
            style="background-image: url('{%static 'home/assets/img/Mainbg8.jpg' %}')">
        </div>
        <div class="container">
            <div class="content">
                <div class="title-area">
                    <p>Reem Hassan</p>
                    <h1 class="title-modern">Crafting Serendipities</h1>
                    <h2>Store</h2>
                        <div class="separator line-separator">♦</div>
                    </div>

                    <div class="button-get-started">
                        <a href=" {% url 'home-main' %}" target="" class="btn btn-white btn-fill btn-lg ">
                            Back To Home
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock NavBar %}

{% block content %}


<hr>
<div id="my-store-17222410"></div>
<div>
    <script data-cfasync="false" type="text/javascript" src="https://app.ecwid.com/script.js?17222410&data_platform=code&data_date=2019-06-14" charset="utf-8"></script><script type="text/javascript"> xProductBrowser("categoriesPerRow=3","views=grid(20,3) list(60) table(60)","categoryView=grid","searchView=list","id=my-store-17222410");</script>
</div>
<hr>
{% endblock content %}

Ibrapp/ibrapp/users/templates/users/profile.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block NavBar %}
{% load static %}

<div class="section section-header-freebie">
    <div class="parallax filter filter-color-red">
        <div class="image"
        style="background-image: url('{%static 'home/assets/img/Mainbg4.jpg' %}')">
    </div>
    <div class="container">
        <div class="content">
            <div class="title-area">
                <h1>Suggestion Profile</h1>

                <div class="button-get-started">
                </div>
                <div class="separator line-separator">♦</div>
            </div>

            <div class="button-get-started">
                <a href=" {% url 'home-main' %}" style="margin-bottom:40px;" target="" class="btn btn-white btn-fill btn-lg ">
                    Back To Home
                </a>
            </div>
        </div>

    </div>
</div>
</div>


{% endblock NavBar %}


{% block content %}

<div class="container">
    <h2>{{user.username}}'s Suggestion Profile</h2>
    <hr>
    <div class="span3 well">
        <center>
            <img src="{{ user.profile.image.url }}" width="180" height="180" class="img-circle">
        </center>
        <p class="description">{{user.email}}</p>
    </div>

    <!-- ProfileUpdateForm() -->
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{u_form|crispy}}
            {{p_form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-danger btn-fill" type="submit">Update</button>
        </div>
    </form>
    <!-- End -->
    <hr>

    <h2>Suggestions History</h2>
    <hr>
    {% if user.post_set.all.count > 0 %}
        {% for post in user.post_set.all %}
             <div class="team">
                                <div class="row">
                                    <div class="col-md-10 col-md-offset-1">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="card card-member">
                                                    <div class="content">
                                                        <div class="description">
                                                            <p class="text-muted">{{post.date_posted|date:"F d, Y" }}</p>
                                                            <h3> {{post.content}}</h3>
                                                        </div>

                                                                <div>
                                                        <a class="btn btn-danger btn-fill btn-sm" type="submit" href="{% url 'suggest-update' post.id %}">Edit Suggestion</a>
                                                                </div>
                                                                 <div>
                                                        <a class="btn btn-danger btn-fill btn-sm" type="submit" href="{% url 'suggest-delete' post.id %}">Delete Suggestion</a>
                                                                </div>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>



        {% endfor %}
    {% else %}
<h4 class="text-muted">No Suggestions</h4>
{% endif %}
    <hr>
</div>
</div>
{% endblock content %}

{% block suggestmain %}{% endblock suggestmain %}